// vue-remote/src/App.vue
<template>
  <section class="card">
    <h2>Vue Remote</h2>
    <p>This panel is served from the Vue + Vite remote.</p>
  </section>
</template>

<style scoped>
.card {
  border-radius: 14px;
  padding: 1.25rem;
  background: linear-gradient(135deg, #0ea5e9, #22c55e);
  color: #06283d;
  font-family: "Avenir Next", "Segoe UI", sans-serif;
  font-weight: 600;
}

h2 {
  margin: 0 0 0.5rem;
}

p {
  margin: 0;
}
</style>

// react-remote/src/App.tsx
function App() {
  return (
    <section
      style={{
        borderRadius: '14px',
        padding: '1.25rem',
        background: 'linear-gradient(135deg, #facc15, #f97316)',
        color: '#431407',
        fontFamily: 'Segoe UI, sans-serif',
        fontWeight: 600,
      }}
    >
      <h2 style={{ margin: '0 0 0.5rem' }}>React Remote</h2>
      <p style={{ margin: 0 }}>This panel is served from the React + Vite remote.</p>
    </section>
  );
}

export default App;
